Core-App/Controllers/ContactSubPlaceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFreamwork;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_App.Controllers
{
    public class ContactSubPlaceController : Controller
    {
        ContactManager _contactManager = new ContactManager(new EfContactDal());
        [HttpGet]
        public IActionResult Index()
        {
            var values=_contactManager.TGetByID(1);
            return View(values);
        }
        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            _contactManager.TUpdate(contact);
            return RedirectToAction("Index");
        }
    }
}

Core-App/Views/ContactSubPlace/Index.cshtml
@model EntityLayer.Concrete.Contact
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "ContactSubPlace", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4> Alt İletişim Bilgileri Düzenleme Paneli</h4>
                <br />
                <form class="forms-sample">
                    <div class="form-group">
                        <label>ID</label>
                        @Html.TextBoxFor(x => x.ContactID, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Telefon</label>
                        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Mail</label>
                        @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        @Html.TextAreaFor(x => x.Description, 6, 3, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>

                </form>
            </div>
        </div>
    </div>
}